// Code generated by validationerrors. DO NOT EDIT.

package dkim2

import "fmt"

// FAIL: Message Instance m=<x> body hash <value> mismatch
type ErrFailMessageInstanceBodyHashValueMismatch struct {
	MInstance int
	Value     string
	Detail    string
}

func (e ErrFailMessageInstanceBodyHashValueMismatch) Error() string {

	s := fmt.Sprintf("FAIL: Message Instance m=%d body hash %s mismatch", e.MInstance, e.Value)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrFailMessageInstanceBodyHashValueMismatch) State() VerificationState {
	return StateFail
}

// FAIL: Message Instance m=<x> header hash <value> mismatch
type ErrFailMessageInstanceHeaderHashValueMismatch struct {
	MInstance int
	Value     string
	Detail    string
}

func (e ErrFailMessageInstanceHeaderHashValueMismatch) Error() string {

	s := fmt.Sprintf("FAIL: Message Instance m=%d header hash %s mismatch", e.MInstance, e.Value)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrFailMessageInstanceHeaderHashValueMismatch) State() VerificationState {
	return StateFail
}

// FAIL: DKIM2-Signature i=<x> public key <value> incorrect signature
type ErrFailSignaturePublicKeyValueIncorrectSignature struct {
	Sequence int
	Value    string
	Detail   string
	Err      error
}

func (e ErrFailSignaturePublicKeyValueIncorrectSignature) Error() string {

	s := fmt.Sprintf("FAIL: DKIM2-Signature i=%d public key %s incorrect signature", e.Sequence, e.Value)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrFailSignaturePublicKeyValueIncorrectSignature) State() VerificationState {
	return StateFail
}

func (e ErrFailSignaturePublicKeyValueIncorrectSignature) Unwrap() error {
	return e.Err
}

// FAIL: DKIM2-Signature i=<x> validation failed
type ErrFailSignatureValidationFailed struct {
	Sequence int
	Detail   string
}

func (e ErrFailSignatureValidationFailed) Error() string {

	s := fmt.Sprintf("FAIL: DKIM2-Signature i=%d validation failed", e.Sequence)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrFailSignatureValidationFailed) State() VerificationState {
	return StateFail
}

// PERMERROR: MAIL FROM and d= do not match
type ErrMailFromAndDoNotMatch struct{}

func (e ErrMailFromAndDoNotMatch) Error() string {

	return fmt.Sprintf("PERMERROR: MAIL FROM and d= do not match")

}

func (_ ErrMailFromAndDoNotMatch) State() VerificationState {
	return StatePermError
}

// PERMERROR: MAIL FROM <value> did not match
type ErrMailFromValueDidNotMatch struct {
	Value string
}

func (e ErrMailFromValueDidNotMatch) Error() string {

	return fmt.Sprintf("PERMERROR: MAIL FROM %s did not match", e.Value)

}

func (_ ErrMailFromValueDidNotMatch) State() VerificationState {
	return StatePermError
}

// PERMERROR Message-Instance m=<x> is not signed
type ErrMessageInstanceIsNotSigned struct {
	MInstance int
}

func (e ErrMessageInstanceIsNotSigned) Error() string {

	return fmt.Sprintf("PERMERROR Message-Instance m=%d is not signed", e.MInstance)

}

func (_ ErrMessageInstanceIsNotSigned) State() VerificationState {
	return StatePermError
}

// PERMERROR Message-Instance m=<x> missing
type ErrMessageInstanceMissing struct {
	MInstance int
}

func (e ErrMessageInstanceMissing) Error() string {

	return fmt.Sprintf("PERMERROR Message-Instance m=%d missing", e.MInstance)

}

func (_ ErrMessageInstanceMissing) State() VerificationState {
	return StatePermError
}

// PERMERROR Message-Instance m=<x> syntax error
type ErrMessageInstanceSyntaxError struct {
	MInstance int
	Header    string
	Detail    string
	Err       error
}

func (e ErrMessageInstanceSyntaxError) Error() string {

	s := fmt.Sprintf("PERMERROR Message-Instance m=%d syntax error", e.MInstance)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrMessageInstanceSyntaxError) State() VerificationState {
	return StatePermError
}

func (e ErrMessageInstanceSyntaxError) Unwrap() error {
	return e.Err
}

// PERMERROR Message-Instance m=<x> tag=<y> missing
type ErrMessageInstanceTagMissing struct {
	MInstance int
	Tag       string
	Header    string
}

func (e ErrMessageInstanceTagMissing) Error() string {

	return fmt.Sprintf("PERMERROR Message-Instance m=%d tag=%s missing", e.MInstance, e.Tag)

}

func (_ ErrMessageInstanceTagMissing) State() VerificationState {
	return StatePermError
}

// PERMERROR: RCPT TO <value> did not match
type ErrRcptToValueDidNotMatch struct {
	Value string
}

func (e ErrRcptToValueDidNotMatch) Error() string {

	return fmt.Sprintf("PERMERROR: RCPT TO %s did not match", e.Value)

}

func (_ ErrRcptToValueDidNotMatch) State() VerificationState {
	return StatePermError
}

// PERMERROR DKIM2-Signature i=<x> signature expired
type ErrSignatureExpired struct {
	Sequence int
}

func (e ErrSignatureExpired) Error() string {

	return fmt.Sprintf("PERMERROR DKIM2-Signature i=%d signature expired", e.Sequence)

}

func (_ ErrSignatureExpired) State() VerificationState {
	return StatePermError
}

// PERMERROR DKIM2-Signature i=<x> missing
type ErrSignatureMissing struct {
	Sequence int
}

func (e ErrSignatureMissing) Error() string {

	return fmt.Sprintf("PERMERROR DKIM2-Signature i=%d missing", e.Sequence)

}

func (_ ErrSignatureMissing) State() VerificationState {
	return StatePermError
}

// PERMERROR: DKIM2-Signature i=<x> public key <value> algorithm mismatch
type ErrSignaturePublicKeyValueAlgorithmMismatch struct {
	Sequence int
	Value    string
}

func (e ErrSignaturePublicKeyValueAlgorithmMismatch) Error() string {

	return fmt.Sprintf("PERMERROR: DKIM2-Signature i=%d public key %s algorithm mismatch", e.Sequence, e.Value)

}

func (_ ErrSignaturePublicKeyValueAlgorithmMismatch) State() VerificationState {
	return StatePermError
}

// PERMERROR: DKIM2-Signature i=<x> public key <value> does not exist
type ErrSignaturePublicKeyValueDoesNotExist struct {
	Sequence int
	Value    string
}

func (e ErrSignaturePublicKeyValueDoesNotExist) Error() string {

	return fmt.Sprintf("PERMERROR: DKIM2-Signature i=%d public key %s does not exist", e.Sequence, e.Value)

}

func (_ ErrSignaturePublicKeyValueDoesNotExist) State() VerificationState {
	return StatePermError
}

// PERMERROR: DKIM2-Signature i=<x> public key <value> has a syntax error
type ErrSignaturePublicKeyValueHasASyntaxError struct {
	Sequence int
	Value    string
	Err      error
	Detail   string
}

func (e ErrSignaturePublicKeyValueHasASyntaxError) Error() string {

	s := fmt.Sprintf("PERMERROR: DKIM2-Signature i=%d public key %s has a syntax error", e.Sequence, e.Value)
	if len(e.Detail) == 0 {
		return s
	}
	return s + " [" + e.Detail + "]"

}

func (_ ErrSignaturePublicKeyValueHasASyntaxError) State() VerificationState {
	return StatePermError
}

func (e ErrSignaturePublicKeyValueHasASyntaxError) Unwrap() error {
	return e.Err
}

// PERMERROR: DKIM2-Signature i=<x> public key <value> has been revoked
type ErrSignaturePublicKeyValueHasBeenRevoked struct {
	Sequence int
	Value    string
}

func (e ErrSignaturePublicKeyValueHasBeenRevoked) Error() string {

	return fmt.Sprintf("PERMERROR: DKIM2-Signature i=%d public key %s has been revoked", e.Sequence, e.Value)

}

func (_ ErrSignaturePublicKeyValueHasBeenRevoked) State() VerificationState {
	return StatePermError
}

// PERMERROR: DKIM2-Signature i=<x> public key <value> has multiple records
type ErrSignaturePublicKeyValueHasMultipleRecords struct {
	Sequence int
	Value    string
}

func (e ErrSignaturePublicKeyValueHasMultipleRecords) Error() string {

	return fmt.Sprintf("PERMERROR: DKIM2-Signature i=%d public key %s has multiple records", e.Sequence, e.Value)

}

func (_ ErrSignaturePublicKeyValueHasMultipleRecords) State() VerificationState {
	return StatePermError
}

// PERMERROR DKIM2-Signature i=<x> syntax error
type ErrSignatureSyntaxError struct {
	Sequence int
	Header   string
	Err      error
}

func (e ErrSignatureSyntaxError) Error() string {

	return fmt.Sprintf("PERMERROR DKIM2-Signature i=%d syntax error", e.Sequence)

}

func (_ ErrSignatureSyntaxError) State() VerificationState {
	return StatePermError
}

func (e ErrSignatureSyntaxError) Unwrap() error {
	return e.Err
}

// PERMERROR DKIM2-Signature i=<x> tag=<y> missing
type ErrSignatureTagMissing struct {
	Sequence int
	Tag      string
	Header   string
}

func (e ErrSignatureTagMissing) Error() string {

	return fmt.Sprintf("PERMERROR DKIM2-Signature i=%d tag=%s missing", e.Sequence, e.Tag)

}

func (_ ErrSignatureTagMissing) State() VerificationState {
	return StatePermError
}

// TEMPERROR: DKIM2-Signature i=<x> public key <value> could not be fetched
type ErrTempSignaturePublicKeyValueCouldNotBeFetched struct {
	Sequence int
	Value    string
	Err      error
}

func (e ErrTempSignaturePublicKeyValueCouldNotBeFetched) Error() string {

	return fmt.Sprintf("TEMPERROR: DKIM2-Signature i=%d public key %s could not be fetched", e.Sequence, e.Value)

}

func (_ ErrTempSignaturePublicKeyValueCouldNotBeFetched) State() VerificationState {
	return StateTempError
}

func (e ErrTempSignaturePublicKeyValueCouldNotBeFetched) Unwrap() error {
	return e.Err
}
