package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"slices"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

type Param struct {
	Name string
	Type string
}
type Message struct {
	Name             string
	Content          string
	Parameters       []Param
	HiddenParameters []Param
	Template         string
	State            string
	HasErr           bool
	HasDetail        bool
}

const structsTpl = `// Code generated by validationerrors. DO NOT EDIT.

package dkim2

import "fmt"

{{ range . }}
// {{ .Content }}
type {{ .Name }} struct {
{{- range .Parameters }}
  {{ .Name }} {{ .Type }}{{ end -}}
{{- range .HiddenParameters }}
  {{ .Name }} {{ .Type }}{{ end -}}
}

func (e {{ .Name }}) Error() string {
{{ if .HasDetail }}
   s := fmt.Sprintf("{{ .Template }}"{{ range .Parameters }}, e.{{ .Name }}{{ end }})
	if len(e.Detail) == 0 {
      return s
    }
   return s + " [" + e.Detail + "]"
{{ else }}
   return fmt.Sprintf("{{ .Template }}"{{ range .Parameters }}, e.{{ .Name }}{{ end }})
{{ end }}
}

func (_ {{ .Name }}) State() VerificationState {
  return {{ .State }}
}

{{ if .HasErr -}}
func (e {{ .Name }}) Unwrap() error {
  return e.Err
}
{{ end }}

{{ end }}
`

var nofmt = false

func main() {
	var labelFile, specFile string
	var printLabels bool
	var outputFile string

	flag.StringVar(&labelFile, "label", "", "Label file to read")
	flag.StringVar(&specFile, "spec", "", "Spec file to read")
	flag.BoolVar(&printLabels, "print-labels", false, "Print labels to stdout")
	flag.StringVar(&outputFile, "output", "", "Go file to write")
	flag.BoolVar(&nofmt, "nofmt", false, "Do not format code")

	flag.Parse()
	if printLabels {
		f, err := os.Open(specFile)
		if err != nil {
			log.Fatal(err)
		}
		defer func(f *os.File) {
			_ = f.Close()
		}(f)

		errorRe := regexp.MustCompile(`^\s+(?:PERMERROR|TEMPERROR|FAIL):?`)
		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			if errorRe.MatchString(line) {
				content := strings.TrimSpace(line)
				name := []string{"Err"}
				words := strings.Fields(content)
				for _, word := range words {
					switch {
					case strings.HasPrefix(word, "PERMERROR"):
					case strings.HasPrefix(word, "TEMPERROR"):
						name = append(name, "temp")
					case strings.HasPrefix(word, "FAIL"):
						name = append(name, "fail")
					case word == "DKIM2-Signature":
						name = append(name, "signature")
					case word == "Message-Instance":
						name = append(name, "message", "instance")
					case strings.HasPrefix(word, "tag="):
						name = append(name, "tag")
					case strings.Contains(word, "="):
					case strings.Contains(word, "<"):
						name = append(name, strings.Trim(word, "<>"))
					default:
						name = append(name, word)
					}
				}
				fmt.Printf("%s: %s\n", strcase.ToCamel(strings.Join(name, "_")), content)
			}
		}
		return
	}

	if labelFile != "" {
		f, err := os.Open(labelFile)
		if err != nil {
			log.Fatal(err)
		}
		defer func(f *os.File) {
			_ = f.Close()
		}(f)
		paramRe := regexp.MustCompile("(?:[a-z]+=)?<[a-z]+>")
		stateRe := regexp.MustCompile(`^(FAIL|TEMPERROR|PERMERROR)`)
		extraRe := regexp.MustCompile(`([A-Za-z0-9]+)\(([^)]*)\)`)
		scanner := bufio.NewScanner(f)
		var msgs []Message
		for scanner.Scan() {
			line := scanner.Text()
			parts := strings.SplitN(line, ": ", 2)
			matches := stateRe.FindStringSubmatch(parts[1])
			if matches == nil {
				log.Fatalf("invalid state: %s", parts[1])
			}
			state := matches[1]
			name := parts[0]
			hasErr := false
			hasDetail := false

			var extraParams []Param
			matches = extraRe.FindStringSubmatch(name)
			if matches != nil {
				name = matches[1]
				for _, extra := range strings.Split(matches[2], ",") {
					extra = strings.TrimSpace(extra)
					switch extra {
					case "Err":
						extraParams = append(extraParams, Param{
							Name: "Err",
							Type: "error",
						})
						hasErr = true
					case "Detail":
						extraParams = append(extraParams, Param{
							Name: "Detail",
							Type: "string",
						})
						hasDetail = true
					default:
						extraParams = append(extraParams, Param{
							Name: extra,
							Type: "string",
						})
					}
				}
			}

			var stateName string
			switch state {
			case "FAIL":
				stateName = "StateFail"
			case "TEMPERROR":
				stateName = "StateTempError"
			case "PERMERROR":
				stateName = "StatePermError"
			}

			msg := Message{
				Name:             name,
				Content:          strings.TrimSpace(parts[1]),
				State:            stateName,
				HiddenParameters: extraParams,
				HasErr:           hasErr,
				HasDetail:        hasDetail,
			}

			msg.Template = paramRe.ReplaceAllStringFunc(msg.Content, func(s string) string {
				switch {
				case strings.HasPrefix(s, "i="):
					msg.Parameters = append(msg.Parameters, Param{
						Name: "Sequence",
						Type: "int",
					})
					return "i=%d"
				case strings.HasPrefix(s, "m="):
					msg.Parameters = append(msg.Parameters, Param{
						Name: "MInstance",
						Type: "int",
					})
					return "m=%d"
				case strings.HasPrefix(s, "tag="):
					msg.Parameters = append(msg.Parameters, Param{
						Name: "Tag",
						Type: "string",
					})
					return "tag=%s"
				default:
					msg.Parameters = append(msg.Parameters, Param{
						Name: "Value",
						Type: "string",
					})
					return "%s"
				}
			})
			msgs = append(msgs, msg)
		}
		slices.SortFunc(msgs, func(a, b Message) int {
			return strings.Compare(a.Name, b.Name)
		})
		err = generateFile(outputFile, structsTpl, msgs)
		if err != nil {
			log.Fatal(err)
		}
	}
}

func generateFile(filename string, tpl string, data any) error {
	t, err := template.New("").Option("missingkey=error").Parse(tpl)
	if err != nil {
		return err
	}
	buf := new(bytes.Buffer)
	err = t.Execute(buf, data)
	if err != nil {
		return err
	}
	generated := buf.Bytes()
	if !nofmt {
		generated, err = format.Source(generated)
		if err != nil {
			return err
		}
	}
	return os.WriteFile(filename, generated, 0644)
}
